version: "3"
services:
# THERE IS ALWAYS ONE ENGINE-X config for all micro-services fix this
  nginx:
    image:  nginx:stable-alpine
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
  user-service:
    build:
      context: ./user-service
      dockerfile: Dockerfile
    image: hijazi313/user-service
    # ports:
    #   - "3000:3000"
    environment:
      - PORT=3000
    depends_on:
      - user-mongo 
  
  user-mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=hijazi313
      - MONGO_INITDB_ROOT_PASSWORD=hijazi313
    volumes:
      - user-mongo-db:/data/db  #NAMED VOLUME

  # user-session-redis:
  #   image: redis 
  #   expose:
  #     - 6379:6379

volumes:
  user-mongo-db: