version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  user-service:
    deploy:
      replicas: 8
      restart_policy:
        condition: any
      update_config:
        parallelism: 2
        delay: 15s
    build: 
      context: ./user-service
      args:
        - NODE_ENV=production
    # volumes:
    #   - ./user-service:/app
    #   - /app/node_modules
    environment:
      - NODE_ENV=production
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
      - MONGO_URI=mongodb://hijazi313:hijazi313@user-mongo:27017/?authSource=admin
    command: node index.js
    # env_file:
    #   - ./.env
  
  user-mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}