version: "3"
services:
  nginx:
    ports:
      - "3000:80"
  user-service:
    build: 
      context: ./user-service
      args:
        - NODE_ENV=development
    volumes:
      - ./user-service:/app:ro # READ ONLY BIND MOUNT VOLUME
      # - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=hijazi313
      - MONGO_PASSWORD=hijazi313
      - MONGO_URI=mongodb://hijazi313:hijazi313@user-mongo:27017/?authSource=admin
    command: npm run dev
    # env_file:
    #   - ./.env