apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  selector:
    app: user-service
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000 # Port on which host is listening
