apiVersion: v1
kind: Service
metadata:
  name: user-mongodb-service
  labels:
    app: user-mongodb
spec:
  clusterIP: None
  selector:
    app: user-mongodb
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
